name: ✨ Feature Request
description: Suggest an idea for this project
title: "[FEATURE REQUEST] "
labels: ["feature"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for your interest in improving krono! Please verify that this feature hasn't been requested before.

  - type: textarea
    id: problem
    attributes:
      label: Is your feature request related to a problem?
      description: A clear and concise description of what the problem is. Ex. I'm always frustrated when...
      placeholder: No, I just want a new feature / Yes, the problem is...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Describe the solution you'd like
      description: A clear and concise description of what you want to happen.
    validations:
      required: true

  - type: textarea
    id: dependencies
    attributes:
      label: Dependencies
      description: Link any related issues or pull requests (e.g. Backend implementation).
      value: |
        - [ ] Backend implementation: 
    validations:
      required: false

  - type: textarea
    id: context
    attributes:
      label: Additional context
      description: Add any other context or screenshots about the feature request here.
    validations:
      required: false